config-version: 1

# The root folder for the database change scripts
root-folder: 'Migration/'


# Define values for the variables to replaced in change scripts
if '{{ env_var('BRANCH_NAME_FOR_CONFIG') }}' == 'main'
then:
  vars:
    VAR_LOAD_DB: 'GLOBAL_LOAD_DB'
    VAR_LOAD_MONDAY_SCHEMA: 'GLOBAL_LOAD_MONDAY_SCMA'
    VAR_REPORTING_DB: 'GLOBAL_REPORTING_DB'
    VAR_BL_SCHEMA: 'GLOBAL_BL_SCMA'
    VAR_REPORTING_SCHEMA: 'GLOBAL_REPORTING_SCMA'
    VAR_ROLE_FOR_MONDAY: 'GLOBAL_DATA_ENGINEER_FR'
    VAR_WH_FOR_MONDAY: 'GLOBAL_DATA_ENGINEER_WH'
